language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

before_install:
  - composer self-update
  - composer --version

install:
  - composer install -o --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - phpcs --extensions=php -n -s .
